---
# tasks file for prepare_overcloud
- name: copy the instackenv.json
  become: true
  copy:
    src: "{{ instackenv_file }}"
    dest: /home/stack/instackenv.json

- name: check if the the instackenv.json exists
  stat:
    path: ~/instackenv.json
  register: instack

- name: Missing instackenv.json
  fail:
    msg: instackenv.json is missing
  when: instack.stat.exists == False

- name: Obtaining images for overcloud nodes
  become: true
  package:
    name: rhosp-director-images
    state: latest

- name: untar the images
  become: yes
  unarchive:
      src: "/usr/share/rhosp-director-images/{{ item }}"
      dest: "~stack/"
      copy: no
      owner: "stack"
      group: "stack"
      list_files: yes
  register: image_files
  with_items: "{{ tar_files }}"
  vars:
    tar_files:
      - "overcloud-full-latest-{{ osp_release }}.tar"
      - "ironic-python-agent-latest-{{ osp_release }}.tar"

- name: import images into director
  shell: |
    source ~/stackrc
    openstack overcloud image upload --image-path /home/stack/
