---
#Prepares the undercloud
- name: Install dependencies
  yum:
    name: "{{ item }}"
  loop:
    - python3-tripleoclient
    - rhosp-release
    - libffi-devel
    - openssl-devel
    - python3-libselinux
  become: true

- name: generate a container image prepare file
  shell: |
    openstack tripleo container image prepare default \
    --local-push-destination \
    --output-env-file containers-prepare-parameter.yaml
  args:
    chdir: /home/stack

- name: append the containerimage registry credentials
  become: true
  become_user: stack
  blockinfile:
    path: /home/stack/containers-prepare-parameter.yaml
    marker: "#<!-- {container_reg} ANSIBLE MANAGED BLOCK -->"
    block: |
      #Adding registry.redhat,io cred
        ContainerImageRegistryLogin: false
        ContainerImageRegistryCredentials:
          registry.redhat.io:
            {{ reg_user }}: {{ reg_password }}

- name: exclude ceph images
  become: true
  become_user: stack
  blockinfile:
    path: /home/stack/containers-prepare-parameter.yaml
    insertafter: "- push_destination: true"
    block: |
      #exclude
          excludes:
          - ceph
          - prometheus

- name: set max_concurrent_builds via hieradata
  copy:
    content: 'nova::compute::ironic::max_concurrent_builds: 5'
    dest: /home/stack/hiera_override.yaml
