---
#Prepares the undercloud
- name: Create a stack user
  user:
    name: "{{ user }}"
    password: "{{ stack_ssh_pass| password_hash('sha512') }}"
    create_home: yes
    home: "/home/{{ user }}"

- name: Add to sudoers
  lineinfile:
    dest: "/etc/sudoers"
    line: "{{ user }} ALL=(root) NOPASSWD:ALL"

- name: generate a container image prepare file
  shell: |
    openstack tripleo container image prepare default \
    --local-push-destination \
    --output-env-file containers-prepare-parameter.yaml
  args:
    chdir: /home/stack

- name: append the containerimage registry credentials
  become: true
  become_user: stack
  blockinfile:
    path: /home/stack/containers-prepare-parameter.yaml
    marker: "#<!-- {container_reg} ANSIBLE MANAGED BLOCK -->"
    block: |
      #Adding registry.redhat,io cred
        ContainerImageRegistryLogin: false
        ContainerImageRegistryCredentials:
          registry.redhat.io:
            "{{ reg_user }}": "{{ reg_password }}"

- name: exclude ceph images
  become: true
  become_user: stack
  blockinfile:
    path: /home/stack/containers-prepare-parameter.yaml
    insertafter: "- push_destination: true"
    block: |
      #exclude
          excludes:
          - ceph
          - prometheus

- name: get the public ip of the undercloud
  shell: |
    ip a | grep int1 | grep inet | awk '{print $2}' | cut -d '/' -f 1
  register: undercloud_ip

- name: add undercloud_host to inventory file
  add_host:
    name: "undercloud"
    groups: "undercloud"
    ansible_host: "{{ undercloud_ip.stdout }}"
    ansible_user: "stack"
    ansible_ssh_pass: "{{ stack_ssh_pass }}"
