---
#Prepares the undercloud
- name: unregister the default rhsm
  redhat_subscription:
    state: absent

- name: Create a stack user
  user:
    name: "{{ user }}"
    password: "{{ stack_ssh_pass }}"
    create_home: yes
    home: "/home/{{ user }}"

- name: Add to sudoers
  lineinfile:
    dest: "/etc/sudoers"
    line: "{{ user }} ALL=(root) NOPASSWD:ALL"

- name: get rhos-release rpms
  shell: |
    wget http://127.0.0.1:8997/rcm-guest/puddles/OpenStack/rhos-release/rhos-release-latest.noarch.rpm
  notify:
    - install rhos-release

- name: add download.devel to /etc/hosts
  shell: |
    echo "127.0.0.1 download.devel.redhat.com" >> /etc/hosts
  notify:
    - install rhos-release
    - modify yum repos

- name: install rhos-release for specific osp version
  shell: |
    rhos-release "{{ osp_version }}" -p passed_phase2 -r "{{ rhel_version }}";
  ignore_errors: yes
  notify:
    - modify yum repos

- name: enable the required virt and container-tools module
  shell: |
    dnf -y module disable virt:rhel container-tools:rhel8;
    dnf -y module enable virt:8.2 container-tools:2.0;
    dnf update -y;

- name: Install required packages
  dnf:
    name: "{{ item }}"
  with_items:
    - python3-tripleoclient
    - rhosp-release

- name: generate a container image prepare file
  shell: |
    openstack tripleo container image prepare default \
    --local-push-destination \
    --output-env-file containers-prepare-parameter.yaml
  remote_user: stack

- name: append the containerimage registry credentials
  remote_user: stack
  blockinfile:
    dest: /home/stack/containers-prepare-parameter.yaml
    block: |
        ContainerImageRegistryLogin: false
        ContainerImageRegistryCredentials:
          registry.redhat.io:
            "{{ reg_user }}": "{{ reg_password }}"

- name: exclude ceph images
  remote_user: stack
  blockinfile:
    dest: /home/stack/containers-prepare-parameter.yaml
    insertafter: "- push_destination: true"
    block: |
          excludes:
          - ceph
          - prometheus

- name: Setup undercloud.conf
  remote_user: stack
  template:
    src: undercloud.conf.j2
    dest: "{{ undercloud_conf }}"
