---
#Prepares the prepare_undercloud

- name: Install dependencies
  yum:
    name: "{{ item }}"
  loop:
    - python3-tripleoclient
    - rhosp-release
    - libffi-devel
    - openssl-devel
    - python3-libselinux
  become: true

- name: generate a container image prepare file
  shell: |
    openstack tripleo container image prepare default \
    --local-push-destination \
    --output-env-file containers-prepare-parameter.yaml
  args:
    chdir: /home/stack

- name: get container image prepare file
  shell: |
    wget 'http://127.0.0.1:8997/rcm-guest/puddles/OpenStack/{{ osp_release }}-RHEL-8/{{ osp_puddle }}/container_image_prepare.yaml'
  args:
    chdir: /home/stack

# The ceph keys that start with 'ceph-' need to be passed into
# 'openstack container image prepare' as 'ceph_'
- name: replace the ceph- with ceph_
  replace:
    path: /home/stack/container_image_prepare.yaml
    regexp: 'ceph-'
    replace: 'ceph_'

- name: set namespace in containers-prepare-parameter.yaml
  replace:
    path: /home/stack/containers-prepare-parameter.yaml
    regexp: '^(\s*namespace:).*'
    replace: "\\1 {{ registry_mirror }}/{{ registry_namespace }}"

- name: set name_prefix in containers-prepare-parameter.yaml
  replace:
    path: /home/stack/containers-prepare-parameter.yaml
    regexp: '(^\ +)name_prefix.*'
    replace: "\\1name_prefix: {{ registry_prefix }}"

- name: get tag info
  shell: |
     cat container_image_prepare.yaml | grep ceph_[A-Za-z] | awk '{$1=$1};1'
  register: tag_info
  args:
    chdir: /home/stack

- name: get ceph info
  shell: |
    cat container_image_prepare.yaml | grep ceph_[A-Za-z]
  register: ceph_info
  args:
    chdir: /home/stack

- name: set tag according to puddle number
  replace:
    path: /home/stack/containers-prepare-parameter.yaml
    regexp: '(^\ +)tag: .*'
    replace: "\\1tag: {{ tag_info.stdout }}"

- name: remove tag_from_label in containers-prepare-parameter.yaml
  lineinfile:
    path: /home/stack/containers-prepare-parameter.yaml
    regexp: '.*tag_from_label.*'
    state: absent

- name: remove ceph containers-prepare-parameter.yaml
  lineinfile:
    path: /home/stack/containers-prepare-parameter.yaml
    regexp: 'ceph_*'
    state: absent

- name: exclude ceph images
  blockinfile:
    path: /home/stack/containers-prepare-parameter.yaml
    insertafter: "- push_destination: true"
    block: |
      #exclude
          excludes:
          - ceph
          - prometheus

- name: append ceph info containers-prepare-parameter.yaml
  lineinfile:
    path: /home/stack/containers-prepare-parameter.yaml
    insertafter: 'set:'
    line: |
      #{{item }}
          {{ item }}
  with_items:
    -  "{{ ceph_info.stdout_lines }}"

- name: add registry_mirror in /etc/hosts
  become: true
  shell: |
    echo "127.0.0.1 {{ registry_mirror }}" >> /etc/hosts

- name: set max_concurrent_builds via hieradata
  copy:
    content: 'nova::compute::ironic::max_concurrent_builds: 5'
    dest: /home/stack/hiera_override.yaml
