---
- name: unregister the default rhsm
  redhat_subscription:
    state: absent

- name: Create a stack user
  user:
    name: "{{ user }}"
    password: "{{ stack_ssh_pass| password_hash('sha512') }}"
    create_home: yes
    home: "/home/{{ user }}"

- name: Add to sudoers
  lineinfile:
    dest: "/etc/sudoers"
    line: "{{ user }} ALL=(root) NOPASSWD:ALL"


- name: remove existing rhos-release files
  shell: |
    rm -rf /etc/yum.repos.d/rhos-*

- name: remove existing rhos-release
  yum:
    name: rhos-release
    state: absent
  ignore_errors: yes

- name: get rhos-release rpms
  shell: |
    wget http://127.0.0.1:8997/rcm-guest/puddles/OpenStack/rhos-release/rhos-release-latest.noarch.rpm
  args:
    chdir: /root/

- name: install rhos-release
  shell: |
    yum clean all -y
    yum install /root/rhos-release-latest.noarch.rpm -y
  ignore_errors: yes

- name: modify yum repos
  shell: |
    for i in $(ls /etc/yum.repos.d/);do sed -i 's/download.devel.redhat.com/127.0.0.1:8998/g' /etc/yum.repos.d/$i; done

- name: install rhos-release for specific osp version
  shell: |
    rhos-release "{{ osp_version }}" -p passed_phase2 -r "{{ rhel_version }}";
  ignore_errors: yes

- name: modify yum repos
  shell: |
    for i in $(ls /etc/yum.repos.d/);do sed -i "{{ item }}" /etc/yum.repos.d/$i; done
  with_items:
    - 's/download.devel.redhat.com/127.0.0.1:8996/g'
    - 's/rhsm-pulp.corp.redhat.com/127.0.0.1:8999/g'

- name: container module
  shell: |
    sudo dnf module disable -y container-tools:rhel8
    sudo dnf module enable -y container-tools:2.0

- name: virt module
  shell: |
     sudo dnf module disable -y virt:rhel
     sudo dnf module enable -y virt:8.2

- name: yum update the system
  yum:
    name:  "*"
    state: latest

#- name: get the public ip of the undercloud
#  shell: |
#    ip a | grep int1 | grep inet | awk '{print $2}' | cut -d '/' -f 1
#  register: undercloud_ip

#- name: add undercloud_host to inventory file
#  add_host:
#    name: "undercloud"
#    groups: "undercloud"
#    ansible_host: "{{ undercloud_ip.stdout }}"
#    ansible_user: "stack"
#    ansible_ssh_pass: "{{ stack_ssh_pass }}"
