---
# vars file for prepare_undercloud
osp_release: 16.1
rhel_version: 8.2
osp_puddle: passed_phase2
user: stack
stack_ssh_pass: stack
controller_count: 1
compute_count: 1
rhel_release: 8.2
undercloud_public_ip: <undercloud_public_ip>
uc_ssh_pass: <undercloud_password>
undercloud_local_interface: int2
clean_nodes: false
undercloud_conf: /home/stack/undercloud.conf
instackenv_file: ~/instackenv.json
external_net_cidr: 172.18.0.0/24
external_allocation_pools_start: 172.18.0.50
external_allocation_pools_end: 172.18.0.150
external_interface_default_route: 172.18.0.1
ext_iface: int3
external_gateway: 172.18.0.1/24
dnf_modules:
  16.1:
    disabled:
      - container-tools:rhel8
      - virt:rhel
    enabled:
      - container-tools:2.0
      - virt:8.2
registry_mirror: redhat.com
registry_namespace: redhat
registry_prefix: rhosp16-openstack-
