---
- name: add undercloud_host to inventory file
  add_host:
    name: "undercloud"
    groups: "undercloud"
    ansible_host: "{{ undercloud_ip }}"
    ansible_user: "root"
    ansible_ssh_pass: "{{ uc_ssh_pass }}"
