---
# tasks file for undercloud
#
- name: Setup undercloud.conf
  template:
    src: undercloud.conf.j2
    dest: "{{ undercloud_conf }}"

- name: Install undercloud
  become: true
  become_user: stack
  shell: |
    openstack undercloud install

- name: Enable Root Login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin yes"
    state: present
    backup: yes
  notify:
    - restart ssh
