---
# tasks file for undercloud
#
- name: Setup undercloud.conf
  template:
    src: undercloud.conf.j2
    dest: "{{ undercloud_conf }}"

- name: Install undercloud
  shell: |
    openstack undercloud install >> undercloud_install.log
  become: true
  become_user: stack
